services:
  - type: web
    name: nutrilabel-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"