import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import { deleteFoodLog, fetchNutritionSummary, fetchNutritionTrends } from '../services/api';

const today = () => new Date().toISOString().slice(0, 10);

export default function NutritionScreen({ navigation }) {
  const [summary, setSummary] = useState(null); const [trends, setTrends] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { try { setError(''); const s = await fetchNutritionSummary(today()); setSummary(s); const t = await fetchNutritionTrends(7); setTrends(t.trends || []); } catch(e) { setError(e.message); } finally { setLoading(false); } };
  useFocusEffect(useCallback(() => { load(); }, []));
  const remove = async (id) => { const ok = Platform.OS === 'web' ? window.confirm('Remove this food from today?') : true; if (!ok) return; try { await deleteFoodLog(id); await load(); } catch(e) { Platform.OS === 'web' ? window.alert(e.message) : Alert.alert('Delete failed', e.message); } };
  const totals = summary?.totals || {}; const goals = summary?.goals || {}; const items = summary?.items || [];
  return <LinearGradient colors={['#FAFDF8','#EEF7E7']} style={styles.flex}><SafeAreaView style={styles.flex}><ScrollView contentContainerStyle={styles.container}>
    <View style={styles.topRow}><Pressable onPress={() => navigation.navigate('Home')}><Ionicons name="arrow-back" size={26} color="#2E7D32" /></Pressable><Text style={styles.topTitle}>Nutrition Tracker</Text><View style={{ width:26 }} /></View>
    <View style={styles.actions}><Pressable style={styles.primary} onPress={() => navigation.navigate('AddFood')}><Text style={styles.primaryText}>+ Add Food</Text></Pressable><Pressable style={styles.secondary} onPress={() => navigation.navigate('GoalSetting')}><Text style={styles.secondaryText}>Set Goals</Text></Pressable></View>
    {loading ? <ActivityIndicator color="#4CAF50" /> : error ? <Text style={styles.error}>{error}</Text> : <>
      <View style={styles.card}><Text style={styles.sectionTitle}>Daily Macro Summary</Text><Macro label="Calories" value={totals.calories} goal={goals.calories} unit="kcal" /><Macro label="Protein" value={totals.protein} goal={goals.protein} unit="g" /><Macro label="Carbs" value={totals.carbs} goal={goals.carbs} unit="g" /><Macro label="Fat" value={totals.fat} goal={goals.fat} unit="g" /><Text style={styles.body}>Missing nutrition values are safely counted as zero instead of guessed.</Text></View>
      <View style={styles.card}><Text style={styles.sectionTitle}>Today’s Food Log</Text>{items.length ? items.map((item) => <Pressable key={item.id} style={styles.foodRow} onLongPress={() => remove(item.id)}><View><Text style={styles.foodName}>{item.food_name}</Text><Text style={styles.body}>{item.serving_size || '1 serving'} • {Math.round(item.calories || 0)} kcal</Text></View><Pressable onPress={() => remove(item.id)}><Ionicons name="trash" size={22} color="#D32F2F" /></Pressable></Pressable>) : <Text style={styles.body}>No foods logged for today.</Text>}</View>
      <View style={styles.card}><Text style={styles.sectionTitle}>7-Day Calorie Trend</Text>{trends.map((day) => <View key={day.date} style={styles.trendRow}><Text style={styles.trendDate}>{day.date.slice(5)}</Text><View style={styles.track}><View style={[styles.fill,{width:`${Math.min(((day.calories||0)/(goals.calories||2000))*100,100)}%`}]} /></View><Text style={styles.trendValue}>{Math.round(day.calories||0)}</Text></View>)}</View>
    </>}
  </ScrollView></SafeAreaView></LinearGradient>;
}
function Macro({ label, value=0, goal=1, unit }) { const pct=Math.min((Number(value||0)/Math.max(Number(goal||1),1))*100,100); return <View style={styles.macro}><View style={styles.macroHeader}><Text style={styles.macroLabel}>{label}</Text><Text style={styles.macroValue}>{Math.round(value)} / {Math.round(goal)} {unit}</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${pct}%`}]} /></View></View>; }
const styles=StyleSheet.create({flex:{flex:1},container:{padding:20,paddingBottom:40},topRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},topTitle:{fontSize:22,fontWeight:'900',color:'#1B5E20'},actions:{flexDirection:'row',gap:10,marginBottom:14},primary:{flex:1,backgroundColor:'#4CAF50',paddingVertical:15,borderRadius:16,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{flex:1,borderWidth:2,borderColor:'#4CAF50',paddingVertical:15,borderRadius:16,alignItems:'center',backgroundColor:'#fff'},secondaryText:{color:'#2E7D32',fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:20,padding:16,borderWidth:1,borderColor:'#DDECCF',marginBottom:14},sectionTitle:{fontSize:20,fontWeight:'900',color:'#1B5E20',marginBottom:10},body:{color:'#5f6f52',fontWeight:'600',lineHeight:20},macro:{marginBottom:12},macroHeader:{flexDirection:'row',justifyContent:'space-between'},macroLabel:{color:'#1B5E20',fontWeight:'900'},macroValue:{color:'#2E7D32',fontWeight:'900'},track:{height:12,backgroundColor:'#E8F5E9',borderRadius:999,overflow:'hidden',marginTop:6,flex:1},fill:{height:12,backgroundColor:'#4CAF50'},foodRow:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,borderTopColor:'#DDECCF',paddingTop:10,marginTop:10},foodName:{color:'#1B5E20',fontWeight:'900'},trendRow:{flexDirection:'row',alignItems:'center',gap:8,marginTop:10},trendDate:{width:45,color:'#1B5E20',fontWeight:'800'},trendValue:{width:45,color:'#2E7D32',fontWeight:'900',textAlign:'right'},error:{color:'#D32F2F',fontWeight:'800'}});
